name: flutter_race_tracking_group16
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0  # Added for HTTP requests
  # cloud_firestore: ^4.8.0  # Commented out
  # firebase_core: ^2.24.2  # Commented out

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
