// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPfFNRY1nyL25TQlSIgigGwFkgRvz_DZk',
    appId: '1:154669926078:web:87be390fc8217358cf40ef',
    messagingSenderId: '154669926078',
    projectId: 'flutter-fire-base-2ac06',
    authDomain: 'flutter-fire-base-2ac06.firebaseapp.com',
    databaseURL: 'https://flutter-fire-base-2ac06-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-fire-base-2ac06.firebasestorage.app',
    measurementId: 'G-B819LYB9NY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6n195kSucG1QQjc6ut8rcQUfLsJ61kVc',
    appId: '1:154669926078:android:3eb84e3403ef10f4cf40ef',
    messagingSenderId: '154669926078',
    projectId: 'flutter-fire-base-2ac06',
    databaseURL: 'https://flutter-fire-base-2ac06-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-fire-base-2ac06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtLQFswxbdQ5235NAm9QJCi8pHM-0P0B8',
    appId: '1:154669926078:ios:0d14f2a2c59909dacf40ef',
    messagingSenderId: '154669926078',
    projectId: 'flutter-fire-base-2ac06',
    databaseURL: 'https://flutter-fire-base-2ac06-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-fire-base-2ac06.firebasestorage.app',
    iosBundleId: 'com.example.flutterRaceTrackingGroup16',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtLQFswxbdQ5235NAm9QJCi8pHM-0P0B8',
    appId: '1:154669926078:ios:0d14f2a2c59909dacf40ef',
    messagingSenderId: '154669926078',
    projectId: 'flutter-fire-base-2ac06',
    databaseURL: 'https://flutter-fire-base-2ac06-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-fire-base-2ac06.firebasestorage.app',
    iosBundleId: 'com.example.flutterRaceTrackingGroup16',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPfFNRY1nyL25TQlSIgigGwFkgRvz_DZk',
    appId: '1:154669926078:web:b04d75bab0cefbcfcf40ef',
    messagingSenderId: '154669926078',
    projectId: 'flutter-fire-base-2ac06',
    authDomain: 'flutter-fire-base-2ac06.firebaseapp.com',
    databaseURL: 'https://flutter-fire-base-2ac06-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-fire-base-2ac06.firebasestorage.app',
    measurementId: 'G-CEEXQGQF2J',
  );
}
